name: Auto Merge Test to Master

on:
  push:
    branches:
      - test

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup GitHub CLI
      - name: Set up GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # Create a Pull Request
      - name: Create a pull request from test to master
        run: |
          gh pr create --base master --head test --title "Auto-merge: test to master" --body "This PR merges the latest changes from test to master." || echo "PR already exists."

      # Merge the Pull Request
      - name: Merge the pull request
        run: |
          PR_ID=$(gh pr list --head test --base master --state open --json number --jq '.[0].number')
          if [ ! -z "$PR_ID" ]; then
            gh pr merge $PR_ID --merge --admin --delete-branch
          else
            echo "No open PR to merge."
          fi
