name: Auto Approve and Merge for Test to Master

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Ensures the workflow can approve and merge PRs

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Check if PR is from `test` to `master`
      - name: Ensure PR is from `test` to `master`
        if: github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'test'
        run: echo "PR is from test to master branch."

      # Step 3: Automatically approve the pull request
      - name: Auto-approve pull request
        if: github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'test'
        uses: hmarr/auto-approve-action@v3

      # Step 4: Automatically merge the pull request
      - name: Auto-merge pull request
        if: github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'test'
        uses: pascalgn/automerge-action@v0.15.0
